---
title: "Client Report - Project 5"
subtitle: "Course DS 250"
author: "Victor Affleck"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

Survey data can be difficult to manage as answers to questions usually aren't uniform, entirely clear, or complied in a way that makes it easy to go over and manipulate later. For this report we will be taking a Star Wars survey and mnipulating the data to better allow both us humans to read it and a machine learning model. 

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/star-wars-survey/StarWars.csv", encoding = 'Latin-1')
```



## Making it easier for the human

Shorten the column names and clean them up for easier use with pandas. Provide a table or list that exemplifies how you fixed the names.









## Making it easier for the machine 

Clean and format the data so that it can be used in a machine learning model. As you format the data, you should complete each item listed below. In your final report provide example(s) of the reformatted data with a short description of the changes made.

a. Filter the dataset to respondents that have seen at least one film.
b. Create a new column that converts the age ranges to a single number. Drop the age range categorical column.
c. Create a new column that converts the education groupings to a single number. Drop the school categorical column
d. Create a new column that converts the income ranges to a single number. Drop the income range categorical column.
e. Create your target (also known as “y” or “label”) column based on the new income range column.
f. One-hot encode all remaining categorical columns.







## Matching up the modified data to the original

Validate that the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article.








## Predicting money makers 

Build a machine learning model that predicts whether a person makes more than $50k. Describe your model and report the accuracy.




